version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=messenger
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/messenger
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=7d
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network


volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 