version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=messenger
    networks:
      - app-network-dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/messenger
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=7d
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network-dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network-dev

volumes:
  mongodb_data_dev:

networks:
  app-network-dev:
    driver: bridge 